name: iweave
description: iWeave - Crafting Unforgettable Experiences, One Tikog at A Time!
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.2
  # Local Persistence
  shared_preferences: ^2.2.3
  # Date formatting
  intl: ^0.19.0
  # Icons
  cupertino_icons: ^1.0.6
  # SQLite Database
  sqflite: ^2.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true